services:
  web:
    build:
      context: .
      args:
        - NODE_VER=${NODE_VER:-lts}
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "[ ! -f Gemfile ] && gem install rails -v '~> ${RAILS_VERSION:-7.0.0}' && rails new . -f -G -d mysql && bundle add sqlite3 --group test ; yarn install && gem install bundler -v '~> ${BUNDLER_VERSION:-2.4.22}' && bundle install && rails db:create && rails db:migrate && rails db:seed && rails assets:precompile && rm -f tmp/pids/server.pid && rails server -b '0.0.0.0' "
    ports:
      - ${PORT:-4004}:${PORT:-4004}
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=${PORT:-4004}
      - RAILS_ENV=${RAILS_ENV:-development}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_URL=mysql2://root:mypasswd@db/${COMPOSE_PROJECT_NAME}_${RAILS_ENV:-development}
      - TEST_DATABASE_URL=sqlite3:db/test.sqlite3
      - RAILS_SERVE_STATIC_FILES=true
      - NODE_OPTIONS=${NODE_OPTIONS}
      - SELENIUM_REMOTE_URL=http://chrome:4444
    env_file:
      - path: ./override.env
        required: false

  db:
    image: mysql
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: mypasswd
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]

  mail:
    image: dockage/mailcatcher
    ports:
      - ${MAILCATCHER_HTTP:-4084}:1080

  chrome:
    image: selenium/standalone-chrome:nightly
    ports:
      - ${VNC_HTTP:-7904}:7900

